# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eksdemo < Formula
  desc "A toolkit to quickly and easily demo EKS with opinioned application installs."
  homepage "https://github.com/aaroniscode/eksdemo"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.0.7/eksdemo_0.0.7_Darwin_arm64.tar.gz"
      sha256 "5f014ecff78f260de0f90c786595bb5d29aea99a8736e889555e7a9ee8622907"

      def install
        bin.install "eksdemo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.0.7/eksdemo_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "dc879ef87f885602def8efaf18092c6ef3ebdff11d8e3132225be66213340259"

      def install
        bin.install "eksdemo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.0.7/eksdemo_0.0.7_Linux_arm64.tar.gz"
      sha256 "19eeb652c27aeefaea28ce5a01ccd96396cdecd2a566e3667d133e52f41e2dbd"

      def install
        bin.install "eksdemo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.0.7/eksdemo_0.0.7_Linux_x86_64.tar.gz"
      sha256 "81a1f3146468eca1261c93deece1dfffa701a689972c8a2a24d46c4f8008b004"

      def install
        bin.install "eksdemo"
      end
    end
  end

  depends_on "weaveworks/tap/eksctl"
end
